project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    self-contained: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default



